### ISSUE TITLE
Task list-GSoC

### ISSUE THREAD

**Issue by Balaje** [Balaje/Gridap.jl#1]
Hi @santiagobadia, @ericneiva and @oriolcg,

I've forked the repository, and the to-do list is below.

- [x] Forked eschnett/Gridap.jl
- [x] Clone and test Erik's branch.
- [ ] Go through and understand Erik's implementation.
- [ ] Add more tests in `test/MultiFieldTests/MultiFieldCellFieldsTests.jl`

**Comment by ericneiva** [comment]
Hi, Balaje, following my discussion via slack:

>  the next step could be to synchronise your local evaluate branch with the latest gridap master changes and check that everything works fine... To this end, there are two steps: (1) bring the changes from gridap/Gridap.jl master branch into your repo evaluate branch and (2) verify that all Gridap tests pass, including the one Erik has for the new functionality.

Just some help for step (1), in case you have never done anything similar. To pull `master` from `gridap/Gridap.jl` you need first to have the git repo of Gridap.jl in gridap as a remote (more info [here](https://docs.github.com/en/github/getting-started-with-github/getting-started-with-git/managing-remote-repositories)):
```
git remote add gridap git@github.com:gridap/Gridap.jl.git
```
Now the new remote should prompt on executing `git remote -v` and you can pull master of gridap repo from your local `eschnett/evaluate` branch:
```
git pull gridap master
```

Could you please update your task list above with this intermediate task?

**Comment by santiagobadia** [comment]
@Balaje when the geometrical part will be done, we want to create a `CellPoint` array with the cell-to-point you have computed (points in the physical space in this case). You can take a look at this struct in `Gridap`. Next, we want to evaluate a `FEfunction` on this `CellPoint` array using `evaluate`. I would also put a test stressing this. Next, Pull Request.
